---
name: CI

on:
  push:
    branches: [ master, develop, ci ]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '2.7'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Ruby cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-

      - name: Bundle
        run: |
          gem update --system
          gem --version
          bundle --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Test
        run: |
          bundle exec rake test
